### ISSUE TITLE
ESI Auth is broken in 5.4.1

### ISSUE THREAD

**Issue by mrambossek** [GoldenGnu/jeveassets#38]
java version "9.0.4"
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)

i keep triggering one of these 2
https://eve.nikr.net/jeveassets/bugs/?version=jEveAssets+5.4.1&java=All&os=Windows+10+10.0&order=Date&desc=DESC&compact=hide&compact=show&wontfix=hide&wontfix=show&reopened=hide&reopened=show&new=hide&new=show&accepted=hide&accepted=show&started=hide&started=show&fixed=hide&fixed=show&fixreleased=hide&fixreleased=show&javabug=hide&javabug=show#bugid644

when i try to edit an existing, or add a new ESI auth. from the log:
INFO: [pool-4-thread-1] net.nikr.eve.jeveasset.io.shared.AbstractGetter - Updated: ESI > Account > <charname> (Completed)
ERROR: [Thread-6] net.nikr.eve.jeveasset.NikrUncaughtExceptionHandler - Uncaught Exception (Thread): java.lang.InterruptedException
java.lang.RuntimeException: java.lang.InterruptedException
	at net.nikr.eve.jeveasset.Program.ensureEDT(Program.java:541)
	at net.nikr.eve.jeveasset.gui.shared.components.JWorking$Worker.run(JWorking.java:129)
Caused by: java.lang.InterruptedException: null
	at java.base/java.lang.Object.wait(Native Method)
	at java.base/java.lang.Object.wait(Unknown Source)
	at java.desktop/java.awt.EventQueue.invokeAndWait(Unknown Source)
	at java.desktop/java.awt.EventQueue.invokeAndWait(Unknown Source)
	at java.desktop/javax.swing.SwingUtilities.invokeAndWait(Unknown Source)
	at net.nikr.eve.jeveasset.Program.ensureEDT(Program.java:539)
	... 1 common frames omitted

possibly a java 9 thing? idk

thanks :)

**Comment by GoldenGnu** [comment]
Thank you for reporting the bug here in GitHub too.
I'm working on fixing this right now and hope to release a bug fix version with the fix later today.

Extra Info:
I implemented a bug fix just before I released 5.4.1 yesterday. Sadly, I didn't test it properly, so, it ended up introducing the bug you're getting now.

**Comment by GoldenGnu** [comment]
Released in 5.4.2
