### ISSUE TITLE
Janice Price API: JsonSyntaxException

### ISSUE THREAD

**Issue by GoldenGnu** [GoldenGnu/jeveassets#469]
```
ERROR: 2024-06-08 09:15:36,699 [Price Fetching 1] uk.me.candle.eve.pricing.impl.Janice - Error fetching price
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2 path $
	at com.google.gson.Gson.fromJson(Gson.java:1003)
	at com.google.gson.Gson.fromJson(Gson.java:956)
	at com.google.gson.Gson.fromJson(Gson.java:905)
	at uk.me.candle.eve.pricing.impl.Janice.fetchPrices(Janice.java:153)
	at uk.me.candle.eve.pricing.AbstractPricing$PriceFetchingThread.run(AbstractPricing.java:458)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2 path $
	at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:350)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:80)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.Gson.fromJson(Gson.java:991)
	... 4 common frames omitted
```

**Comment by GoldenGnu** [comment]
Released in 7.9.1 (Hopefully)
